# Generated by Django 5.1 on 2024-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('customer', models.CharField(max_length=255)),
                ('items', models.JSONField()),
            ],
        ),
    ]
