# Generated by Django 5.1 on 2024-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
    ]
