# Generated by Django 5.1 on 2024-09-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('debit_account_name', models.CharField(max_length=255)),
                ('credit_account_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
